'addon: a11y': ["addons/a11y/**"]
'addon: actions': ["addons/actions/**"]
'addon: backgrounds': ["addons/backgrounds/**"]
'addon: events ': ["addons/events/**"]
'addon: graphql ': ["addons/graphql/**"]
'addon: info': ["addons/info/**"]
'addon: jest': ["addons/jest/**"]
'addon: knobs': ["addons/knobs/**"]
'addon: links': ["addons/links/**"]
'addon: notes': ["addons/notes/**"]
'addon: options': ["addons/options/**"]
'addon: storyshots': ["addons/storyshots/**"]
'addon: viewport': ["addons/viewport/**"]
'app: angular': ["app/angular/**"]
'app: preact': ["app/preact/**"]
'app: rax': ["app/rax/**"]
'app: react': ["app/react/**"]
'app: vue': ["app/vue/**"]
'app: svelte': ["app/svelte/**"]
'app: mithril': ["app/mithril/**"]
'babel / webpack': ["webpack", "babel"]
'cli': ["lib/cli/**"]
'compatibility with other tools': []
'documentation': ["docs", "*.md"]
'ui': ["lib/ui"]
