on: label
name: Dangerfile JS Label
jobs:
  dangerJS:
    name: Danger JS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Danger JS
      uses: danger/danger-js@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: --dangerfile .ci/danger/dangerfile.ts
