on: pull_request
name: Automention PRs
jobs:
  automention:
    name: Automention
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Automention
      uses: shilman/automention@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
